castellum/contacts/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .views import StreetView

app_name = 'contacts'
urlpatterns = [
    path('streets/', StreetView.as_view(), name='streets'),
]

castellum/recruitment/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.urls import path

from .feeds import AppointmentFeedForResource
from .feeds import AppointmentFeedForStudy
from .feeds import FollowUpFeedForStudy
from .feeds import FollowUpFeedForUser
from .views import AdditionalInfoUpdateView
from .views import AppointmentsUpdateView
from .views import AttributesUpdateView
from .views import CalendarView
from .views import ConsentChangeView
from .views import ContactUpdateView
from .views import ContactView
from .views import DataProtectionUpdateView
from .views import ExcludeView
from .views import LegalRepresentativeContactUpdateView
from .views import MailRecruitmentCleanupView
from .views import MailRecruitmentRemindView
from .views import MailRecruitmentView
from .views import RecruitmentCleanupView
from .views import RecruitmentViewExcluded
from .views import RecruitmentViewInvited
from .views import RecruitmentViewOpen
from .views import ReportView

app_name = 'recruitment'
urlpatterns = [
    path('followups/', FollowUpFeedForUser.as_view(), name='followups-user-feed'),
    path(
        'resources/<int:pk>/',
        AppointmentFeedForResource.as_view(),
        name='resource-feed',
    ),
    path('<int:study_pk>/', RecruitmentViewOpen.as_view(), name='recruitment-open'),
    path(
        '<int:study_pk>/invited/',
        RecruitmentViewInvited.as_view(),
        name='recruitment-invited',
    ),
    path(
        '<int:study_pk>/excluded/',
        RecruitmentViewExcluded.as_view(),
        name='recruitment-excluded',
    ),
    path('<int:study_pk>/mail/', MailRecruitmentView.as_view(), name='mail'),
    path(
        '<int:study_pk>/mail/<int:pk>/remind/',
        MailRecruitmentRemindView.as_view(),
        name='mail-remind',
    ),
    path(
        '<int:study_pk>/mail/<int:pk>/cleanup/',
        MailRecruitmentCleanupView.as_view(),
        name='mail-cleanup',
    ),
    path('<int:study_pk>/cleanup/', RecruitmentCleanupView.as_view(), name='cleanup'),
    path('<int:pk>/calendar/', CalendarView.as_view(), name='calendar'),
    path(
        '<int:pk>/calendar/feed/',
        AppointmentFeedForStudy.as_view(),
        name='calendar-feed',
    ),
    path(
        '<int:study_pk>/followups/',
        FollowUpFeedForStudy.as_view(),
        name='followups-feed',
    ),
    path('<int:study_pk>/<int:pk>/', ContactView.as_view(), name='contact'),
    path('<int:study_pk>/<int:pk>/exclude/', ExcludeView.as_view(), name='exclude'),
    path('<int:study_pk>/<int:pk>/report/', ReportView.as_view(), name='report'),
    path(
        '<int:study_pk>/<int:pk>/appointments/',
        AppointmentsUpdateView.as_view(),
        name='appointments',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-contact/',
        ContactUpdateView.as_view(),
        name='contact-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-attributes/',
        AttributesUpdateView.as_view(),
        name='attributes-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-data-protection/',
        DataProtectionUpdateView.as_view(),
        name='data-protection-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-data-protection/consent/',
        ConsentChangeView.as_view(),
        name='consent-change',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-additional-info/',
        AdditionalInfoUpdateView.as_view(),
        name='additional-info-update',
    ),
    path(
        '<int:study_pk>/<int:participation_pk>/representatives/<hash>/update-contact/',
        LegalRepresentativeContactUpdateView.as_view(),
        name='legal-representative-contact-update',
    ),
]

castellum/subjects/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.urls import path

from .api import APIAttributesView
from .views import AdditionalInfoUpdateView
from .views import AttributesUpdateView
from .views import ConsentChangeView
from .views import ContactUpdateView
from .views import DataProtectionUpdateView
from .views import DeleteRecruitmentDataView
from .views import LegalRepresentativeSearchView
from .views import MaintenanceAttributesView
from .views import MaintenanceConsentView
from .views import MaintenanceContactView
from .views import MaintenanceDuplicatesView
from .views import MaintenanceEstrangedSubjectsView
from .views import MaintenanceReliabilityView
from .views import MaintenanceSubjectCreationRequestView
from .views import ParticipationAddView
from .views import ParticipationDeleteView
from .views import ParticipationListView
from .views import ParticipationRecruitView
from .views import ReportDetailView
from .views import ReportView
from .views import SubjectAuditTrailView
from .views import SubjectCreationRequestDeleteView
from .views import SubjectDeleteView
from .views import SubjectDetailView
from .views import SubjectExportView
from .views import SubjectPseudonymsView
from .views import SubjectPseudonymView
from .views import SubjectResolveView
from .views import SubjectSearchView

app_name = 'subjects'
urlpatterns = [
    path('', SubjectSearchView.as_view(), name='index'),
    path('resolve/', SubjectResolveView.as_view(), name='resolve'),
    path(
        'representatives/',
        LegalRepresentativeSearchView.as_view(),
        name='legal-representative-search',
    ),
    path(
        'maintenance/attributes/',
        MaintenanceAttributesView.as_view(),
        name='maintenance-attributes',
    ),
    path(
        'maintenance/contact/',
        MaintenanceContactView.as_view(),
        name='maintenance-contact',
    ),
    path(
        'maintenance/consent/',
        MaintenanceConsentView.as_view(),
        name='maintenance-consent',
    ),
    path(
        'maintenance/duplicates/',
        MaintenanceDuplicatesView.as_view(),
        name='maintenance-duplicates',
    ),
    path(
        'maintenance/reliability/',
        MaintenanceReliabilityView.as_view(),
        name='maintenance-reliability',
    ),
    path(
        'maintenance/estranged-subjects/',
        MaintenanceEstrangedSubjectsView.as_view(),
        name='maintenance-estranged-subjects',
    ),
    path(
        'maintenance/subjectcreationrequest/',
        MaintenanceSubjectCreationRequestView.as_view(),
        name='maintenance-subjectcreationrequest',
    ),
    path(
        'subjectcreationrequest/<int:pk>/delete/',
        SubjectCreationRequestDeleteView.as_view(),
        name='maintenance-subjectcreationrequest-delete',
    ),
    path('<uuid:pk>/', SubjectDetailView.as_view(), name='detail'),
    path('<uuid:pk>/pseudonyms/', SubjectPseudonymsView.as_view(), name='pseudonyms'),
    path(
        '<uuid:pk>/pseudonyms/<domain>/',
        SubjectPseudonymView.as_view(),
        name='pseudonym',
    ),
    path('<uuid:pk>/delete/', SubjectDeleteView.as_view(), name='delete'),
    path('<uuid:pk>/export/', SubjectExportView.as_view(), name='export'),
    path('<uuid:pk>/contact/', ContactUpdateView.as_view(), name='contact'),
    path('<uuid:pk>/attributes/', AttributesUpdateView.as_view(), name='attributes'),
    path(
        '<uuid:pk>/attributes/delete/',
        DeleteRecruitmentDataView.as_view(),
        name='delete-recruitment-data',
    ),
    path(
        '<uuid:pk>/data-protection/',
        DataProtectionUpdateView.as_view(),
        name='data-protection',
    ),
    path(
        '<uuid:pk>/data-protection/consent/',
        ConsentChangeView.as_view(),
        name='consent',
    ),
    path(
        '<uuid:pk>/additional-info/',
        AdditionalInfoUpdateView.as_view(),
        name='additional-info',
    ),
    path(
        '<uuid:pk>/participations/',
        ParticipationListView.as_view(),
        name='participation-list',
    ),
    path(
        '<uuid:pk>/participations/recruit/',
        ParticipationRecruitView.as_view(),
        name='participation-recruit',
    ),
    path(
        '<uuid:pk>/participations/add/',
        ParticipationAddView.as_view(),
        name='participation-add',
    ),
    path(
        '<uuid:subject_uuid>/participations/<int:pk>/delete/',
        ParticipationDeleteView.as_view(),
        name='participation-delete',
    ),
    path('<uuid:pk>/report/', ReportView.as_view(), name='report'),
    path('reports/<int:pk>/', ReportDetailView.as_view(), name='report-detail'),
]

if settings.CASTELLUM_AUDIT_TRAIL_ENABLED:
    urlpatterns += [
        path(
            '<uuid:pk>/audit-trail/',
            SubjectAuditTrailView.as_view(),
            name='audit-trail',
        ),
    ]

if settings.CASTELLUM_API_ENABLED:
    urlpatterns += [
        path(
            'api/subjects/<uuid:domain>/<pseudonym>/attributes/',
            APIAttributesView.as_view(),
        ),
    ]

castellum/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from bootstrap_colors.views import BootstrapColorsView
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.urls import include
from django.urls import path
from django.views.decorators.cache import cache_control
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from mfa.decorators import public as mfa_public
from mfa.views import LoginView
from stronghold.decorators import public

from castellum.castellum_auth.forms import AuthenticationForm
from castellum.castellum_auth.views import set_language
from castellum.execution.views import ExecutionProtectedMediaView
from castellum.execution.views import StudyConsentProtectedMediaView
from castellum.recruitment.views import RecruitmentProtectedMediaView
from castellum.studies.models import Resource
from castellum.studies.models import Study
from castellum.studies.views.studies import StudyProtectedMediaView
from castellum.subjects.views import SubjectProtectedMediaView
from castellum.utils.views import ProtectedMediaView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'


class FeedsView(LoginRequiredMixin, TemplateView):
    template_name = 'feeds.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['resources'] = Resource.objects.all()
        context['studies'] = self.request.user.study_set.filter(status=Study.EXECUTION)
        return context


def dummy(request):
    return HttpResponse('', status=204)


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(
        template_name='login.html',
        authentication_form=AuthenticationForm,
    ), name='login'),
    path('logout/', mfa_public(LogoutView.as_view()), name='logout'),
    path('favicon.ico', mfa_public(public(
        RedirectView.as_view(url='/static/images/favicon.ico')
    ))),
    path('colors.css', mfa_public(public(cache_control(max_age=86400)(
        BootstrapColorsView.as_view()
    ))), name='colors'),
    path('ping/', dummy, name='ping'),
    path('feeds/', FeedsView.as_view(), name='feeds'),

    path('i18n/', mfa_public(set_language), name='set_language'),

    path('admin/', admin.site.urls),
    path('studies/', include('castellum.studies.urls', namespace='studies')),
    path('subjects/', include('castellum.subjects.urls', namespace='subjects')),
    path('contacts/', include('castellum.contacts.urls', namespace='contacts')),
    path(
        'recruitment/', include('castellum.recruitment.urls', namespace='recruitment')
    ),
    path('execution/', include('castellum.execution.urls', namespace='execution')),
    path('', include('castellum.appointments.urls', namespace='appointments')),
    path(
        'data-protection/',
        include('castellum.data_protection.urls', namespace='data_protection'),
    ),
    path('mfa/', include('mfa.urls', namespace='mfa')),

    path('media/studies/<int:pk>/<path:path>', StudyProtectedMediaView.as_view()),
    path(
        'media/recruitment/<int:study_pk>/<int:pk>/<path:path>',
        RecruitmentProtectedMediaView.as_view(),
        name='recruitment-media',
    ),
    path(
        'media/execution/<int:study_pk>/<int:pk>/<path:path>',
        ExecutionProtectedMediaView.as_view(),
        name='execution-media',
    ),
    path(
        'media/studyconsents/<int:study_pk>/<int:pk>/<filename>',
        StudyConsentProtectedMediaView.as_view(),
        name='studyconsent-media',
    ),
    path(
        'media/subjects/<uuid:uuid>/<path:path>',
        SubjectProtectedMediaView.as_view(),
        name='subject-media',
    ),
    path('media/consent/<path:path>', ProtectedMediaView.as_view(prefix='consent')),
]

if 'model_stats' in settings.INSTALLED_APPS:
    urlpatterns = [
        path('admin/stats/', include('model_stats.urls')),
        *urlpatterns,
    ]

try:
    import debug_toolbar

    urlpatterns = [
        *urlpatterns,
        path('__debug__/', include(debug_toolbar.urls)),
    ]
except ImportError:
    pass

castellum/recruitment/models/subjectfilters.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.db import models
from django.urls import reverse

from castellum.studies.models import Study
from castellum.subjects.models import Subject

from ..models import Attribute


class SubjectFilterGroupManager(models.Manager):
    def clone(self, original_group):
        cloned_group = SubjectFilterGroup.objects.create(study=original_group.study)
        SubjectFilter.objects.bulk_create(
            self.clone_filters(original_group, cloned_group)
        )
        return cloned_group

    def clone_filters(self, original_group, cloned_group):
        for f in original_group.subjectfilter_set.all():
            yield SubjectFilter(
                group=cloned_group,
                attribute=f.attribute,
                operator=f.operator,
                value=f.value,
            )


class SubjectFilterGroup(models.Model):
    study = models.ForeignKey(Study, on_delete=models.CASCADE)

    objects = SubjectFilterGroupManager()

    def get_absolute_url(self):
        return reverse('studies:filtergroup-update', args=[self.study.pk, self.pk])

    def get_potential_matches(self):
        from .. import filter_queries

        return Subject.objects.filter(
            filter_queries.study_recruitable(self.study, enable_filters=False),
            filter_queries.subjectfilters(self),
            filter_queries.already_in_study(self.study, include_recruitment=False),
        )


class SubjectFilter(models.Model):
    group = models.ForeignKey(SubjectFilterGroup, on_delete=models.CASCADE)
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    operator = models.CharField(max_length=64)
    value = models.JSONField(editable=True)

    def __str__(self):
        return self.attribute.field.get_filter_display(self.operator, self.value)

    def to_q(self, include_unknown=True):
        return self.attribute.field.filter_to_q(
            self.operator, self.value, include_unknown
        )

castellum/contacts/views.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import ListView

from .models import Street


class StreetView(LoginRequiredMixin, ListView):
    model = Street
    ordering = 'name'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(name__istartswith=self.request.GET['q'])
        return qs[:10]

    def get(self, request, *args, **kwargs):
        data = [street.name for street in self.get_queryset()]
        return JsonResponse({'streets': data})

castellum/recruitment/templates/recruitment/age_widget.html
<div class="row gx-2">
    {% for widget in widget.subwidgets %}
        <div class="col-sm">
            {% include widget.template_name %}
        </div>
    {% endfor %}
</div>

castellum/recruitment/templates/recruitment/base.html
{% extends "base_with_breadcrumbs.html" %}

{% load i18n %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'studies:index' %}">{% translate "Studies" %}</a></li>
    {% if study %}
        <li class="breadcrumb-item"><a {% if study.status == study.EXECUTION %}href="{% url 'recruitment:recruitment-open' study.pk %}"{% endif %}>{% translate 'Recruitment for' %} {{ study.name }}</a></li>
    {% endif %}
    {% if participation %}
        <li class="breadcrumb-item"><a {% if study.status == study.EXECUTION %}href="{% url 'recruitment:contact' study.pk participation.pk %}"{% endif %}>{{ participation.subject.contact.short_name }}</a></li>
    {% endif %}
{% endblock %}

castellum/recruitment/templates/recruitment/confirm_exclude.html
{% extends "recruitment/base.html" %}
{% load static i18n %}

{% block title %}{% translate "Exclude subject" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            {% blocktranslate %}Are you sure you want to exclude this subject from {{ study }}?{% endblocktranslate %}
            {% translate 'Alternatively you could ask another recruiter with a higher privacy level to contact this subject.' %}
        </p>
        <div class="d-print-none mb-3">
            <a href="{% url 'recruitment:recruitment-open' study.pk %}" class="btn btn-outline-primary mb-1" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger mb-1">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

castellum/recruitment/templates/recruitment/mail_cleanup.html
{% extends "recruitment/base.html" %}
{% load i18n %}

{% block title %}{% translate "Cleanup" context 'verb' %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>{% blocktranslate with count=object.participation_set.count date=object.datetime|date %}Are you sure you want to move {{ count }} pending participations that belong to the batch that was sent on {{ date }} to the "excluded"-tab?{% endblocktranslate %}</p>
        <div class="d-print-none mb-3">
            <a href="{% url 'recruitment:mail' study.pk %}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

castellum/recruitment/templates/recruitment/participation_base.html
{% extends "recruitment/base.html" %}
{% load i18n auth utils %}

{% block title %}{{ study }} &middot; {{ block.super }}{% endblock %}

{% block header %}
    <div class="container text-center my-4">
        <h1>
            <svg class="identicon" data-jdenticon-value="{{ participation.pk }}" aria-hidden="true"></svg>
            {{ subject.contact.full_name }}
        </h1>
        <span class="badge text-bg-secondary" title="{{ participation.TOOLTIPS.get_status_tooltip }}">{{ participation|display:'status' }}</span>
        {% if not subject.is_available %}
            <span class="list-icon text-bg-warning" title="{% blocktranslate with next_available=subject.not_available_until %}not available until {{ next_available }}{% endblocktranslate %}">{% icon 'phone-slash' %}</span>
        {% endif %}
        {% if CASTELLUM_REPORT_NOTIFICATION_TO and not subject.blocked %}
            <a href="{% url 'recruitment:report' study.pk participation.pk %}" class="btn btn-sm btn-light">{% icon 'flag' %} {% translate 'report' %}</a>
        {% endif %}
    </div>

    <nav class="d-print-none" aria-label="{% translate 'Tabs' %}">
        <ul class="nav nav-tabs justify-content-center mb-3">
            <li class="nav-item">
                <a href="{% url 'recruitment:contact' study.pk participation.pk %}" class="nav-link {% if view.tab == 'contact' %}active{% endif %}">
                    {% translate 'Contact' %}
                </a>
            </li>

            {% has_perm 'appointments.change_appointment' user study as can_change_appointment %}
            {% if can_change_appointment and study.studysession_set.exists %}
                <li class="nav-item">
                    <a href="{% url 'recruitment:appointments' study.pk participation.pk %}" class="nav-link {% if view.tab == 'appointments' %}active{% endif %}">
                        {% translate 'Appointments' %}
                    </a>
                </li>
            {% endif %}

            {% has_perm 'subjects.change_subject' user study as can_change_subject %}
            {% if can_change_subject %}
                <li class="nav-item">
                    <a href="{% url 'recruitment:contact-update' study.pk participation.pk %}" class="nav-link {% if view.tab == 'update-data' %}active{% endif %}">
                        {% translate 'Update data' %}
                        {% if subject.consent_action_required or not subject.contact.is_complete %}
                            {% icon 'exclamation-triangle' label=_('Action required') %}
                        {% endif %}
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

castellum/recruitment/templates/recruitment/participation_update_base.html
{% extends "recruitment/participation_base.html" %}
{% load i18n utils %}

{% block container_class %}container-lg{% endblock %}

{% block content_with_messages %}
    <div class="row">
        <div class="col-md-3">
            <nav class="list-group mb-3" aria-label="{% translate 'Subtabs' %}">
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'contact' %}active{% endif %}" href="{% url 'recruitment:contact-update' study.pk participation.pk %}">
                    {% translate 'Contact' %}
                    {% if not subject.contact.is_complete %}
                        {% icon 'exclamation-triangle' label=_('Action required') %}
                    {% endif %}
                </a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'attributes' %}active{% endif %}" href="{% url 'recruitment:attributes-update' study.pk participation.pk %}">{% translate 'Recruitment attributes' %}</a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'data-protection' %}active{% endif %}" href="{% url 'recruitment:data-protection-update' study.pk participation.pk %}">
                    {% translate 'Data protection' %}
                    {% if subject.consent_action_required %}
                        {% icon 'exclamation-triangle' label=_('Action required') %}
                    {% endif %}
                </a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'additional-info' %}active{% endif %}" href="{% url 'recruitment:additional-info-update' study.pk participation.pk %}">
                    {% translate 'Additional Info' %}
                </a>
            </nav>
        </div>

        <div class="col-md-9">
            {{ block.super }}
        </div>
    </div>
{% endblock %}

castellum/recruitment/templates/recruitment/recruitment.html
{% extends "recruitment/recruitment_base.html" %}
{% load i18n static auth %}

{% block title %}{% translate "Recruitment" %} &middot; {{ study }} &middot; {{ block.super }}{% endblock %}

{% block content %}

    {% if statistics %}
        <details class="mb-4">
            <summary class="mb-2">{% translate 'Statistics' %}</summary>
            {{ statistics|safe }}
        </details>
    {% endif %}

    <div class="d-flex justify-content-between">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link {% if view.subtab == 'open' %}active{% endif %}" href="{% url 'recruitment:recruitment-open' study.pk %}">
                    {% translate 'Open' %}
                    <span class="badge text-bg-light">{{ open_count }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view.subtab == 'invited' %}active{% endif %}" href="{% url 'recruitment:recruitment-invited' study.pk %}">
                    {% translate 'Participating' %}
                    <span class="badge text-bg-light">{{ invited_count }}/{{ study.min_subject_count }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view.subtab == 'excluded' %}active{% endif %}" href="{% url 'recruitment:recruitment-excluded' study.pk %}">
                    {% translate 'Excluded' %}
                    <span class="badge text-bg-light">{{ excluded_count }}</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled">{% translate 'All' context 'total' %} <span class="badge text-bg-light">{{ all_count }}</span></a>
            </li>
        </ul>

        {% if view.subtab == 'open' %}
            <form class="dropdown" method="get">
                <button class="btn btn-outline-primary dropdown-toggle" type="button" id="sortDropdownButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ sort_label }}
                </button>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="sortDropdownButton">
                    {% for key, label in sort_options %}
                        <button class="dropdown-item" name="sort" value="{{ key }}">{{ label }}</button>
                    {% endfor %}
                </div>
            </form>
        {% endif %}
    </div>

    <!-- Tab panes -->
    <div class="tab-content">
        <div class="tab-pane active">
            {% include "recruitment/__recruitment_list.html" %}
        </div>
    </div>

    {% if view.subtab == 'open' %}
        <div class="d-print-none mb-3">
            <form method="post" class="d-inline">
                {% csrf_token %}
                <button class="btn btn-primary">{% translate 'Add' %}</button>
            </form>
            <a class="btn btn-secondary" href="{% url 'recruitment:cleanup' study.pk %}">{% translate 'Cleanup' %}…</a>
        </div>
    {% endif %}
{% endblock %}

castellum/recruitment/templates/recruitment/recruitment_base.html
{% extends "recruitment/base.html" %}
{% load i18n static auth %}

{% block title %}{{ study }} &middot; {{ block.super }}{% endblock %}

{% block header %}

    <div class="container text-center my-4">
        <h1>{{ study.name }}</h1>
    </div>

    <nav class="d-print-none" aria-label="{% translate 'Tabs' %}">
        <ul class="nav nav-tabs justify-content-center mb-3">
            <li class="nav-item">
                <a class="nav-link {% if view.tab == 'recruitment' %}active{% endif %}" href="{% url 'recruitment:recruitment-open' study.pk %}">{% translate 'Recruitment' %}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if view.tab == 'mail' %}active{% endif %}" href="{% url 'recruitment:mail' study.pk %}">{% translate 'Mail' %}</a>
            </li>
        </ul>
    </nav>

{% endblock %}