castellum/execution/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.urls import path

from .api import APIAttributesView
from .api import APIDomainsView
from .api import APIPseudonymsView
from .api import APIResolveView
from .api import APIValidateView
from .feeds import AppointmentFeedForUser
from .views import AdditionalInfoUpdateView
from .views import AttributesUpdateView
from .views import CalendarView
from .views import ConsentChangeView
from .views import ContactUpdateView
from .views import DataProtectionUpdateView
from .views import ExclusionCriteriaView
from .views import ExportView
from .views import LegalRepresentativeContactUpdateView
from .views import NewsMailView
from .views import ParticipationAppointmentsUpdateView
from .views import ParticipationConsentCreateView
from .views import ParticipationConsentDeleteView
from .views import ParticipationConsentView
from .views import ParticipationDetailView
from .views import ParticipationDropoutConfirmView
from .views import ParticipationListView
from .views import ParticipationPseudonymsView
from .views import ParticipationPseudonymView
from .views import ParticipationStatusView
from .views import ParticipationUpdateView
from .views import ProgressView
from .views import ReportView
from .views import ResolveView
from .views import TagView

app_name = 'execution'
urlpatterns = [
    path('calendar/feed/', AppointmentFeedForUser.as_view(), name='calendar-user-feed'),
    path('<int:study_pk>/', ParticipationListView.as_view(), name='participation-list'),
    path('<int:study_pk>/resolve/', ResolveView.as_view(), name='resolve'),
    path('<int:study_pk>/news/', NewsMailView.as_view(), name='news-mail'),
    path('<int:pk>/calendar/', CalendarView.as_view(), name='calendar'),
    path('<int:pk>/criteria/', ExclusionCriteriaView.as_view(), name='criteria'),
    path('<int:pk>/export/', ExportView.as_view(), name='export'),
    path('<int:pk>/progress/', ProgressView.as_view(), name='progress'),
    path('<int:pk>/tags/', TagView.as_view(), name='execution-tags'),
    path(
        '<int:study_pk>/<int:pk>/',
        ParticipationDetailView.as_view(),
        name='participation-detail',
    ),
    path(
        '<int:study_pk>/<int:pk>/pseudonyms/',
        ParticipationPseudonymsView.as_view(),
        name='participation-pseudonyms',
    ),
    path(
        '<int:study_pk>/<int:pk>/pseudonyms/<domain>/',
        ParticipationPseudonymView.as_view(),
        name='participation-pseudonym',
    ),
    path(
        '<int:study_pk>/<int:pk>/status/',
        ParticipationStatusView.as_view(),
        name='participation-status',
    ),
    path(
        '<int:study_pk>/<int:pk>/dropout/confirm/',
        ParticipationDropoutConfirmView.as_view(),
        name='participation-dropout-confirm',
    ),
    path(
        '<int:study_pk>/<int:pk>/update/',
        ParticipationUpdateView.as_view(),
        name='participation-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/consent/',
        ParticipationConsentView.as_view(),
        name='participation-consent',
    ),
    path(
        '<int:study_pk>/<int:pk>/consent/add/',
        ParticipationConsentCreateView.as_view(),
        name='participation-consent-create',
    ),
    path(
        '<int:study_pk>/<int:pk>/consent/<int:consent_pk>/delete/',
        ParticipationConsentDeleteView.as_view(),
        name='participation-consent-delete',
    ),
    path(
        '<int:study_pk>/<int:pk>/appointments/',
        ParticipationAppointmentsUpdateView.as_view(),
        name='participation-appointments',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-contact/',
        ContactUpdateView.as_view(),
        name='contact-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-attributes/',
        AttributesUpdateView.as_view(),
        name='attributes-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-data-protection/',
        DataProtectionUpdateView.as_view(),
        name='data-protection-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-data-protection/consent/',
        ConsentChangeView.as_view(),
        name='consent-change',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-additional-info/',
        AdditionalInfoUpdateView.as_view(),
        name='additional-info-update',
    ),
    path(
        '<int:study_pk>/<int:participation_pk>/representatives/<hash>/update-contact/',
        LegalRepresentativeContactUpdateView.as_view(),
        name='legal-representative-contact-update',
    ),
    path('<int:study_pk>/<int:pk>/report/', ReportView.as_view(), name='report'),
]

if settings.CASTELLUM_API_ENABLED:
    urlpatterns += [
        path('api/studies/<int:pk>/domains/', APIDomainsView.as_view()),
        path(
            'api/studies/<int:pk>/domains/<uuid:domain>/', APIPseudonymsView.as_view()
        ),
        path(
            'api/studies/<int:pk>/domains/<uuid:domain>/<pseudonym>/',
            APIValidateView.as_view(),
        ),
        path(
            'api/studies/<int:study_pk>/domains/<uuid:domain>/<pseudonym>/attributes/',
            APIAttributesView.as_view(),
        ),
        path(
            'api/studies/<int:study_pk>/domains/<uuid:domain>/<pseudonym>/<uuid:target_domain>/',
            APIResolveView.as_view(),
        ),
    ]

castellum/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from bootstrap_colors.views import BootstrapColorsView
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.urls import include
from django.urls import path
from django.views.decorators.cache import cache_control
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from mfa.decorators import public as mfa_public
from mfa.views import LoginView
from stronghold.decorators import public

from castellum.castellum_auth.forms import AuthenticationForm
from castellum.castellum_auth.views import set_language
from castellum.execution.views import ExecutionProtectedMediaView
from castellum.execution.views import StudyConsentProtectedMediaView
from castellum.recruitment.views import RecruitmentProtectedMediaView
from castellum.studies.models import Resource
from castellum.studies.models import Study
from castellum.studies.views.studies import StudyProtectedMediaView
from castellum.subjects.views import SubjectProtectedMediaView
from castellum.utils.views import ProtectedMediaView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'


class FeedsView(LoginRequiredMixin, TemplateView):
    template_name = 'feeds.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['resources'] = Resource.objects.all()
        context['studies'] = self.request.user.study_set.filter(status=Study.EXECUTION)
        return context


def dummy(request):
    return HttpResponse('', status=204)


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(
        template_name='login.html',
        authentication_form=AuthenticationForm,
    ), name='login'),
    path('logout/', mfa_public(LogoutView.as_view()), name='logout'),
    path('favicon.ico', mfa_public(public(
        RedirectView.as_view(url='/static/images/favicon.ico')
    ))),
    path('colors.css', mfa_public(public(cache_control(max_age=86400)(
        BootstrapColorsView.as_view()
    ))), name='colors'),
    path('ping/', dummy, name='ping'),
    path('feeds/', FeedsView.as_view(), name='feeds'),

    path('i18n/', mfa_public(set_language), name='set_language'),

    path('admin/', admin.site.urls),
    path('studies/', include('castellum.studies.urls', namespace='studies')),
    path('subjects/', include('castellum.subjects.urls', namespace='subjects')),
    path('contacts/', include('castellum.contacts.urls', namespace='contacts')),
    path(
        'recruitment/', include('castellum.recruitment.urls', namespace='recruitment')
    ),
    path('execution/', include('castellum.execution.urls', namespace='execution')),
    path('', include('castellum.appointments.urls', namespace='appointments')),
    path(
        'data-protection/',
        include('castellum.data_protection.urls', namespace='data_protection'),
    ),
    path('mfa/', include('mfa.urls', namespace='mfa')),

    path('media/studies/<int:pk>/<path:path>', StudyProtectedMediaView.as_view()),
    path(
        'media/recruitment/<int:study_pk>/<int:pk>/<path:path>',
        RecruitmentProtectedMediaView.as_view(),
        name='recruitment-media',
    ),
    path(
        'media/execution/<int:study_pk>/<int:pk>/<path:path>',
        ExecutionProtectedMediaView.as_view(),
        name='execution-media',
    ),
    path(
        'media/studyconsents/<int:study_pk>/<int:pk>/<filename>',
        StudyConsentProtectedMediaView.as_view(),
        name='studyconsent-media',
    ),
    path(
        'media/subjects/<uuid:uuid>/<path:path>',
        SubjectProtectedMediaView.as_view(),
        name='subject-media',
    ),
    path('media/consent/<path:path>', ProtectedMediaView.as_view(prefix='consent')),
]

if 'model_stats' in settings.INSTALLED_APPS:
    urlpatterns = [
        path('admin/stats/', include('model_stats.urls')),
        *urlpatterns,
    ]

try:
    import debug_toolbar

    urlpatterns = [
        *urlpatterns,
        path('__debug__/', include(debug_toolbar.urls)),
    ]
except ImportError:
    pass

castellum/execution/forms.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django import forms
from django.utils.translation import gettext_lazy as _


class NewsMailForm(forms.Form):
    subject = forms.CharField(label=_('E-mail subject'), required=True)
    body = forms.CharField(
        label=_('E-mail body'),
        help_text=_(
            'Any "{name}"-tags included in the e-mail-body will '
            'automatically be replaced with the full name of the subject.'
        ),
        widget=forms.Textarea,
        required=True,
    )

castellum/execution/templates/execution/calendar.html
{% extends "execution/study_base.html" %}
{% load static %}

{% block container_class %}container-lg{% endblock%}

{% block content %}
    <div class="my-5" data-js="calendar"></div>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'fullcalendar.js' %}"></script>
    <script src="{% static '@fullcalendar/bootstrap/index.global.min.js' %}"></script>
    <script src="{% static '@fullcalendar/core/locales/de.global.min.js' %}"></script>
    <script type="module" src="{% static 'js/calendar.js' %}"></script>
{% endblock %}

{% block extra_styles %}
    <link rel="stylesheet" href="{% static 'fullcalendar.css' %}">
{% endblock %}

castellum/execution/templates/execution/participation_base.html
{% extends "execution/base.html" %}
{% load i18n auth utils %}

{% block title %}{{ study }} &middot; {{ block.super }}{% endblock %}

{% block header %}
    <div class="container text-center my-4">
        <h1>
            <svg class="identicon" data-jdenticon-value="{{ participation.pk }}" aria-hidden="true"></svg>
            {{ subject.contact.full_name }}
        </h1>
        {% for tag in participation.execution_tags.all %}
            <span class="badge text-bg-{{ tag.color }}">{{ tag }}</span>
        {% endfor %}
        {% if participation.status not in participation.DEFAULT_SET %}
            <span class="badge text-bg-secondary" title="{{ participation.get_status_tooltip }}">{{ participation|display:'status' }}</span>
        {% endif %}
        {% if not subject.is_available %}
            <span class="list-icon text-bg-warning" title="{% blocktranslate with next_available=subject.not_available_until %}not available until {{ next_available }}{% endblocktranslate %}">{% icon 'phone-slash' %}</span>
        {% endif %}
        {% if CASTELLUM_REPORT_NOTIFICATION_TO and not subject.blocked %}
            <a href="{% url 'execution:report' study.pk participation.pk %}" class="btn btn-sm btn-light">{% icon 'flag' %} {% translate 'report' %}</a>
        {% endif %}
    </div>

    <nav class="d-print-none" aria-label="{% translate 'Tabs' %}">
        <ul class="nav nav-tabs justify-content-center mb-3">
            <li class="nav-item">
                <a href="{% url 'execution:participation-detail' study.pk participation.pk %}" class="nav-link {% if view.tab == 'overview' %}active{% endif %}">{% translate 'Overview' %}</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'execution:participation-consent' study.pk participation.pk %}" class="nav-link {% if view.tab == 'consent' %}active{% endif %}">{% translate 'Study consent' %}</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'execution:participation-update' study.pk participation.pk %}" class="nav-link {% if view.tab == 'update' %}active{% endif %}">{% translate 'Hints' %}</a>
            </li>

            {% has_perm 'appointments.change_appointment' user study as can_change_appointment %}
            {% if can_change_appointment and study.studysession_set.exists %}
                <li class="nav-item">
                    <a href="{% url 'execution:participation-appointments' study.pk participation.pk %}" class="nav-link {% if view.tab == 'appointments' %}active{% endif %}">{% translate 'Appointments' %}</a>
                </li>
            {% endif %}

            {% has_perm 'subjects.change_subject' user study as can_change_subject %}
            {% if can_change_subject %}
                <li class="nav-item">
                    <a href="{% url 'execution:contact-update' study.pk participation.pk %}" class="nav-link {% if view.tab == 'update-data' %}active{% endif %}">
                        {% translate 'Update data' %}
                        {% if subject.consent_action_required or not subject.contact.is_complete %}
                            {% icon 'exclamation-triangle' label=_('Action required') %}
                        {% endif %}
                    </a>
                </li>
            {% endif %}

            <li class="nav-item">
                <a href="{% url 'execution:participation-status' study.pk participation.pk %}" class="nav-link {% if view.tab == 'status' %}active{% endif %}">{% translate 'Status' %}</a>
            </li>
        </ul>
    </nav>
{% endblock %}

castellum/execution/templates/execution/participation_criteria.html
{% extends "execution/study_base.html" %}
{% load i18n utils %}

{% block content %}
    {% if study.recruitment_text %}
        {{ study.recruitment_text|urlize|linebreaks }}
    {% endif %}
    {% if CASTELLUM_GENERAL_RECRUITMENT_TEXT %}
        <details class="mb-3">
            <summary class="mb-2">{% translate 'General recruitment text' %}</summary>
            <blockquote class="blockquote">
                {{ CASTELLUM_GENERAL_RECRUITMENT_TEXT|urlize|linebreaks }}
            </blockquote>
        </details>
    {% endif %}
    {% for study_type in study.study_type.all %}
        {% if study_type.exclusion_criteria %}
            <details class="mb-3">
                <summary class="mb-2">{% translate 'Criteria for:' %} {{ study_type.label }}</summary>
                <blockquote class="blockquote">
                    {{ study_type.exclusion_criteria|urlize|linebreaks }}
                </blockquote>
            </details>
        {% endif %}
    {% endfor %}
{% endblock %}

castellum/execution/templates/execution/participation_dropout_confirm.html
{% extends "execution/participation_base.html" %}
{% load i18n %}

{% block title %}{% translate "Dropped out" context 'verb' %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            {% translate 'Are you sure you want to remove this participation?' %}
            {% translate 'Note that all appointments related to it will be <strong>permanently deleted</strong>.' %}
        </p>
        <label class="form-check mb-3">
            <input type="checkbox" class="form-check-input" data-js="confirm-delete">
            <span class="form-check-label">{% translate "I have made sure that all external data related to this study participation has been destroyed" %}</span>
        </label>
        <div class="d-print-none mb-3">
            <a href="{% url 'execution:participation-status' study.pk object.pk %}" class="btn btn-outline-primary" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger" disabled>{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

castellum/execution/templates/execution/participation_hints.html
{% extends "execution/participation_base.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <form method="post">
        {% include 'utils/form_errors.html' with form=form %}
        {% csrf_token %}

        {% bootstrap_field form.news_interest %}
        {% bootstrap_field form.was_reliable %}

        {% if study.executiontag_set.exists %}
            <div class="mb-3">
                {{ form.execution_tags.label }}

                {% for value, label in form.execution_tags.field.choices %}
                    <label class="form-check mb-0">
                        <input type="checkbox" class="form-check-input" name="execution_tags" value="{{ value }}" {% if value.instance.id in form.execution_tags.value %}checked{% endif %}>
                        <span class="form-check-label">
                            <span class="badge text-bg-{{ value.instance.color }}">{{ label }}</span>
                        </span>
                    </label>
                {% endfor %}
                <small><a href="{% url 'execution:execution-tags' study.pk %}">{% translate 'Manage tags' %}</a></small>
            </div>
        {% endif %}

        <button class="btn btn-primary">{% translate 'Save' %}</button>
    </form>
{% endblock %}

castellum/execution/templates/execution/participation_list.html
{% extends "execution/study_base.html" %}
{% load i18n auth utils %}

{% block content %}
    {% if sort_options|length > 1 %}
        <div class="d-flex justify-content-end">
            <form class="dropdown" method="get">
                <button class="btn btn-outline-primary dropdown-toggle" type="button" id="sortDropdownButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ sort_label }}
                </button>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="sortDropdownButton">
                    {% for key, label in sort_options %}
                        <button class="dropdown-item" name="sort" value="{{ key }}">
                            {% if label.color %}
                                <span class="badge text-bg-{{ label.color }}">{{ label }}</span>
                            {% else %}
                                {{ label }}
                            {% endif %}
                        </button>
                    {% endfor %}
                </div>
            </form>
        </div>
    {% endif %}
    <ul class="table-list mt-3">
        {% for participation in object_list %}
            <li class="table-list-item">
                {% has_privacy_level participation.subject.privacy_level user as can_access %}
                {% if can_access %}
                    <svg class="identicon my-1 me-2" data-jdenticon-value="{{ participation.pk }}" aria-hidden="true"></svg>
                    <div class="d-inline-block my-1 me-2 {% if participation.status == participation.PARTICIPATING_DROPPED_OUT or participation.subject.blocked or participation.subject.deceased %}text-body-secondary{% endif %}">
                        <div>
                            {{ participation.subject.contact.full_name }}
                            {% if participation.subject.privacy_level > 0 %}
                                <span class="badge {% if participation.subject.privacy_level > study.members_min_privacy_level %}text-bg-warning{% else %}text-bg-secondary{% endif %}">
                                    {% icon 'user-shield' label=_('Privacy level') %}
                                    {{ participation.subject.get_effective_privacy_level }}
                                    {% if participation.subject.privacy_level > study.members_min_privacy_level %}
                                        {% icon 'warning' label=_('Not all members of this study can access this subject') %}
                                    {% endif %}
                                </span>
                            {% endif %}
                            {% if session_count > 0 %}
                                <span class="badge text-bg-secondary my-1" title="{% blocktranslate with count=participation.appointment_count total=session_count %}{{ count }} out of {{ total }} appointments have already been scheduled{% endblocktranslate %}">
                                    {% icon 'calendar' label=_('Appointments') %}
                                    {{ participation.appointment_count }}/{{ session_count }}
                                    {% if participation.appointment_today %}
                                        {% translate 'today' %}
                                    {% endif %}
                                </span>
                            {% endif %}
                            {% for tag in participation.execution_tags.all %}
                                <span class="badge text-bg-{{ tag.color }} my-1">{{ tag }}</span>
                            {% endfor %}
                            {% if participation.status not in participation.DEFAULT_SET %}
                                <span class="badge text-bg-secondary my-1" title="{{ participation.get_status_tooltip }}">{{ participation|display:'status' }}</span>
                            {% endif %}
                            {% if participation.subject.blocked %}
                                <span class="badge text-bg-dark my-1" title="{{ participation.subject.TOOLTIPS.blocked }}">{{ participation.subject|verbose_name:'blocked' }}</span>
                            {% endif %}
                            {% if participation.subject.deceased %}
                                <span class="badge text-bg-dark my-1" title="{{ participation.subject.TOOLTIPS.deceased }}">{{ participation.subject|verbose_name:'deceased' }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="table-list-item-actions">
                        <a class="btn btn-outline-primary my-1" href="{% url 'execution:participation-detail' study.pk participation.pk %}">{% translate 'Details' %}</a>
                    </div>
                {% else %}
                    <div class="text-body-secondary">
                        <div class="d-inline-block my-1 me-2">
                            {% translate 'insufficient privacy level' %}
                            <span class="list-icon text-bg-danger">{% icon 'ban' %}</span>
                        </div>
                    </div>
                {% endif %}
            </li>
        {% empty %}
            <li class="alert alert-warning">{% translate 'No participations found' %}</li>
        {% endfor %}
    </ul>
{% endblock %}

castellum/execution/templates/execution/participation_pseudonyms.html
{% extends "execution/participation_base.html" %}
{% load i18n utils %}

{% block title %}{% translate 'Pseudonyms' %} &middot; {{ block.super }}{% endblock %}

{% block header %}{% endblock %}

{% block content %}
    <table class="table">
        <thead>
            <tr>
                <th>{% translate 'List key' %}</th>
                <th>{% translate 'List name' %}</th>
                <th>{% translate 'Pseudonym' %}</th>
            </tr>
        </thead>
        <tbody>
            {% for domain in domains %}
                <tr>
                    <td>{{ domain|display:'key' }}</dt>
                    <td>{{ domain|display:'name' }}</dt>
                    <td>
                        <a href="{% url 'execution:participation-pseudonym' study.pk view.kwargs.pk domain.key %}" data-js="replace-me" class="btn btn-sm btn-secondary">
                            {% translate 'get pseudonym' %}
                        </a>
                    </dt>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3"><em>{% translate 'No pseudonym lists' %}</em></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

castellum/execution/templates/execution/participation_update_base.html
{% extends "execution/participation_base.html" %}
{% load i18n utils %}

{% block container_class %}container-lg{% endblock %}

{% block content_with_messages %}
    <div class="row">
        <div class="col-md-3">
            <nav class="list-group mb-3" aria-label="{% translate 'Subtabs' %}">
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'contact' %}active{% endif %}" href="{% url 'execution:contact-update' study.pk participation.pk %}">
                    {% translate 'Contact' %}
                    {% if not subject.contact.is_complete %}
                        {% icon 'exclamation-triangle' label=_('Action required') %}
                    {% endif %}
                </a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'attributes' %}active{% endif %}" href="{% url 'execution:attributes-update' study.pk participation.pk %}">{% translate 'Recruitment attributes' %}</a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'data-protection' %}active{% endif %}" href="{% url 'execution:data-protection-update' study.pk participation.pk %}">
                    {% translate 'Data protection' %}
                    {% if subject.consent_action_required %}
                        {% icon 'exclamation-triangle' label=_('Action required') %}
                    {% endif %}
                </a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'additional-info' %}active{% endif %}" href="{% url 'execution:additional-info-update' study.pk participation.pk %}">
                    {% translate 'Additional Info' %}
                </a>
            </nav>
        </div>

        <div class="col-md-9">
            {{ block.super }}
        </div>
    </div>
{% endblock %}

castellum/execution/templates/execution/participationconsent_base.html
{% extends "execution/participation_base.html" %}
{% load i18n %}

{% block title %}
    {% translate "Study consent" %} &middot; {{ block.super }}
{% endblock %}

castellum/execution/templates/execution/participationconsent_confirm_delete.html
{% extends "execution/participationconsent_base.html" %}
{% load i18n %}

{% block title %}{% translate "Delete" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>{% translate "Are you sure you want to <strong>permanently delete</strong> this study consent?" %}</p>
        <div class="d-print-none mb-3">
            <a href="{{ view.get_success_url }}" class="btn btn-outline-primary" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

castellum/execution/templates/execution/participationconsent_form.html
{% extends "execution/participationconsent_base.html" %}
{% load i18n django_bootstrap5 %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% include 'utils/form_errors.html' with form=form %}
        {% csrf_token %}

        {% bootstrap_field form.name required_css_class='castellum-required' %}
        {% bootstrap_field form.file required_css_class='castellum-required' %}

        <div class="d-print-none mb-3">
            <a href="{{ view.get_success_url }}" class="btn btn-outline-primary" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-primary">{% translate 'Save' %}</button>
        </div>
    </form>
{% endblock %}

castellum/execution/templates/execution/study_export.html
{% extends "execution/study_base.html" %}
{% load i18n django_bootstrap5 %}

{% block title %}{% translate 'Export' %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="get">
        {% include 'utils/form_errors.html' with form=form %}
        {% bootstrap_field form.domain %}
        <button class="btn btn-primary">{% translate 'Export' %}</button>
    </form>
{% endblock %}

castellum/execution/templates/execution/study_news_mail.html
{% extends "execution/study_base.html" %}
{% load i18n django_bootstrap5 humanize utils %}

{% block content %}
    <p>{% translate 'This form allows you to send a message to all subjects who indicated interest in study news. You cannot attach a document to the email, but you can include a link.' %}</p>

    <form method="post">
        {% include 'utils/form_errors.html' with form=form %}
        {% csrf_token %}

        {% bootstrap_field form.subject %}
        {% bootstrap_field form.body %}

        <div class="d-print-none mb-3">
            <button class="btn btn-primary">{% translate 'Send' %}</button>
            <button name="testmail" class="btn btn-secondary">{% translate 'Send test mail to myself' %}</button>
        </div>
    </form>

    {% if study.newsmailbatch_set.all %}
        <h3 class="mt-5">{% translate "Previous mails" %}</h3>
        <ul class="table-list mb-3">
        {% for batch in study.newsmailbatch_set.all reversed %}
            <li class="table-list-item">
                <div>
                    <small class="text-body-secondary">
                        {% blocktranslate with datetime=batch.datetime|longdate counter=forloop.revcounter|ordinal %}
                            {{ counter }} mail sent on {{ datetime }}:
                        {% endblocktranslate %}
                    </small>
                    <div>
                        {% blocktranslate with contacted_size=batch.contacted_size other_size=batch.other_size %}
                            {{ contacted_size }} subjects contacted, {{ other_size }} had to be contacted via postal mail
                        {% endblocktranslate %}
                    </div>
                    <details>
                        <summary>{{ batch.mail_subject }}</summary>
                        {{ batch.mail_body|linebreaks }}
                    </details>
                </div>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
{% endblock %}