castellum/subjects/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.urls import path

from .api import APIAttributesView
from .views import AdditionalInfoUpdateView
from .views import AttributesUpdateView
from .views import ConsentChangeView
from .views import ContactUpdateView
from .views import DataProtectionUpdateView
from .views import DeleteRecruitmentDataView
from .views import LegalRepresentativeSearchView
from .views import MaintenanceAttributesView
from .views import MaintenanceConsentView
from .views import MaintenanceContactView
from .views import MaintenanceDuplicatesView
from .views import MaintenanceEstrangedSubjectsView
from .views import MaintenanceReliabilityView
from .views import MaintenanceSubjectCreationRequestView
from .views import ParticipationAddView
from .views import ParticipationDeleteView
from .views import ParticipationListView
from .views import ParticipationRecruitView
from .views import ReportDetailView
from .views import ReportView
from .views import SubjectAuditTrailView
from .views import SubjectCreationRequestDeleteView
from .views import SubjectDeleteView
from .views import SubjectDetailView
from .views import SubjectExportView
from .views import SubjectPseudonymsView
from .views import SubjectPseudonymView
from .views import SubjectResolveView
from .views import SubjectSearchView

app_name = 'subjects'
urlpatterns = [
    path('', SubjectSearchView.as_view(), name='index'),
    path('resolve/', SubjectResolveView.as_view(), name='resolve'),
    path(
        'representatives/',
        LegalRepresentativeSearchView.as_view(),
        name='legal-representative-search',
    ),
    path(
        'maintenance/attributes/',
        MaintenanceAttributesView.as_view(),
        name='maintenance-attributes',
    ),
    path(
        'maintenance/contact/',
        MaintenanceContactView.as_view(),
        name='maintenance-contact',
    ),
    path(
        'maintenance/consent/',
        MaintenanceConsentView.as_view(),
        name='maintenance-consent',
    ),
    path(
        'maintenance/duplicates/',
        MaintenanceDuplicatesView.as_view(),
        name='maintenance-duplicates',
    ),
    path(
        'maintenance/reliability/',
        MaintenanceReliabilityView.as_view(),
        name='maintenance-reliability',
    ),
    path(
        'maintenance/estranged-subjects/',
        MaintenanceEstrangedSubjectsView.as_view(),
        name='maintenance-estranged-subjects',
    ),
    path(
        'maintenance/subjectcreationrequest/',
        MaintenanceSubjectCreationRequestView.as_view(),
        name='maintenance-subjectcreationrequest',
    ),
    path(
        'subjectcreationrequest/<int:pk>/delete/',
        SubjectCreationRequestDeleteView.as_view(),
        name='maintenance-subjectcreationrequest-delete',
    ),
    path('<uuid:pk>/', SubjectDetailView.as_view(), name='detail'),
    path('<uuid:pk>/pseudonyms/', SubjectPseudonymsView.as_view(), name='pseudonyms'),
    path(
        '<uuid:pk>/pseudonyms/<domain>/',
        SubjectPseudonymView.as_view(),
        name='pseudonym',
    ),
    path('<uuid:pk>/delete/', SubjectDeleteView.as_view(), name='delete'),
    path('<uuid:pk>/export/', SubjectExportView.as_view(), name='export'),
    path('<uuid:pk>/contact/', ContactUpdateView.as_view(), name='contact'),
    path('<uuid:pk>/attributes/', AttributesUpdateView.as_view(), name='attributes'),
    path(
        '<uuid:pk>/attributes/delete/',
        DeleteRecruitmentDataView.as_view(),
        name='delete-recruitment-data',
    ),
    path(
        '<uuid:pk>/data-protection/',
        DataProtectionUpdateView.as_view(),
        name='data-protection',
    ),
    path(
        '<uuid:pk>/data-protection/consent/',
        ConsentChangeView.as_view(),
        name='consent',
    ),
    path(
        '<uuid:pk>/additional-info/',
        AdditionalInfoUpdateView.as_view(),
        name='additional-info',
    ),
    path(
        '<uuid:pk>/participations/',
        ParticipationListView.as_view(),
        name='participation-list',
    ),
    path(
        '<uuid:pk>/participations/recruit/',
        ParticipationRecruitView.as_view(),
        name='participation-recruit',
    ),
    path(
        '<uuid:pk>/participations/add/',
        ParticipationAddView.as_view(),
        name='participation-add',
    ),
    path(
        '<uuid:subject_uuid>/participations/<int:pk>/delete/',
        ParticipationDeleteView.as_view(),
        name='participation-delete',
    ),
    path('<uuid:pk>/report/', ReportView.as_view(), name='report'),
    path('reports/<int:pk>/', ReportDetailView.as_view(), name='report-detail'),
]

if settings.CASTELLUM_AUDIT_TRAIL_ENABLED:
    urlpatterns += [
        path(
            '<uuid:pk>/audit-trail/',
            SubjectAuditTrailView.as_view(),
            name='audit-trail',
        ),
    ]

if settings.CASTELLUM_API_ENABLED:
    urlpatterns += [
        path(
            'api/subjects/<uuid:domain>/<pseudonym>/attributes/',
            APIAttributesView.as_view(),
        ),
    ]

castellum/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from bootstrap_colors.views import BootstrapColorsView
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.urls import include
from django.urls import path
from django.views.decorators.cache import cache_control
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from mfa.decorators import public as mfa_public
from mfa.views import LoginView
from stronghold.decorators import public

from castellum.castellum_auth.forms import AuthenticationForm
from castellum.castellum_auth.views import set_language
from castellum.execution.views import ExecutionProtectedMediaView
from castellum.execution.views import StudyConsentProtectedMediaView
from castellum.recruitment.views import RecruitmentProtectedMediaView
from castellum.studies.models import Resource
from castellum.studies.models import Study
from castellum.studies.views.studies import StudyProtectedMediaView
from castellum.subjects.views import SubjectProtectedMediaView
from castellum.utils.views import ProtectedMediaView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'


class FeedsView(LoginRequiredMixin, TemplateView):
    template_name = 'feeds.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['resources'] = Resource.objects.all()
        context['studies'] = self.request.user.study_set.filter(status=Study.EXECUTION)
        return context


def dummy(request):
    return HttpResponse('', status=204)


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(
        template_name='login.html',
        authentication_form=AuthenticationForm,
    ), name='login'),
    path('logout/', mfa_public(LogoutView.as_view()), name='logout'),
    path('favicon.ico', mfa_public(public(
        RedirectView.as_view(url='/static/images/favicon.ico')
    ))),
    path('colors.css', mfa_public(public(cache_control(max_age=86400)(
        BootstrapColorsView.as_view()
    ))), name='colors'),
    path('ping/', dummy, name='ping'),
    path('feeds/', FeedsView.as_view(), name='feeds'),

    path('i18n/', mfa_public(set_language), name='set_language'),

    path('admin/', admin.site.urls),
    path('studies/', include('castellum.studies.urls', namespace='studies')),
    path('subjects/', include('castellum.subjects.urls', namespace='subjects')),
    path('contacts/', include('castellum.contacts.urls', namespace='contacts')),
    path(
        'recruitment/', include('castellum.recruitment.urls', namespace='recruitment')
    ),
    path('execution/', include('castellum.execution.urls', namespace='execution')),
    path('', include('castellum.appointments.urls', namespace='appointments')),
    path(
        'data-protection/',
        include('castellum.data_protection.urls', namespace='data_protection'),
    ),
    path('mfa/', include('mfa.urls', namespace='mfa')),

    path('media/studies/<int:pk>/<path:path>', StudyProtectedMediaView.as_view()),
    path(
        'media/recruitment/<int:study_pk>/<int:pk>/<path:path>',
        RecruitmentProtectedMediaView.as_view(),
        name='recruitment-media',
    ),
    path(
        'media/execution/<int:study_pk>/<int:pk>/<path:path>',
        ExecutionProtectedMediaView.as_view(),
        name='execution-media',
    ),
    path(
        'media/studyconsents/<int:study_pk>/<int:pk>/<filename>',
        StudyConsentProtectedMediaView.as_view(),
        name='studyconsent-media',
    ),
    path(
        'media/subjects/<uuid:uuid>/<path:path>',
        SubjectProtectedMediaView.as_view(),
        name='subject-media',
    ),
    path('media/consent/<path:path>', ProtectedMediaView.as_view(prefix='consent')),
]

if 'model_stats' in settings.INSTALLED_APPS:
    urlpatterns = [
        path('admin/stats/', include('model_stats.urls')),
        *urlpatterns,
    ]

try:
    import debug_toolbar

    urlpatterns = [
        *urlpatterns,
        path('__debug__/', include(debug_toolbar.urls)),
    ]
except ImportError:
    pass

castellum/studies/views/api.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.http import JsonResponse
from django.views.generic import View

from castellum.castellum_auth.mixins import APIAuthMixin
from castellum.castellum_auth.mixins import PermissionRequiredMixin

from ..mixins import StudyMixin
from ..models import Study


class APIStudyListView(APIAuthMixin, View):
    def get_queryset(self):
        qs = Study.objects.all()
        if self.request.GET.get('status') in ['edit', 'draft']:
            qs = qs.filter(status=Study.DRAFT)
        elif self.request.GET.get('status') == 'execution':
            qs = qs.filter(status=Study.EXECUTION)
        elif self.request.GET.get('status') == 'finished':
            qs = qs.filter(status=Study.FINISHED)
        return qs

    def get(self, request, **kwargs):
        pks = self.get_queryset().values_list('pk', flat=True)
        return JsonResponse({'studies': list(pks)})


class APIStudyDetailView(APIAuthMixin, StudyMixin, PermissionRequiredMixin, View):
    permission_required = ['studies.view_study']

    def get(self, request, **kwargs):
        return JsonResponse(self.study.export())

castellum/studies/views/members.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later


from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext_noop
from django.views.generic import DeleteView
from django.views.generic import FormView
from django.views.generic.detail import SingleObjectMixin

from castellum.audit.helpers import audit
from castellum.castellum_auth.mixins import PermissionRequiredMixin
from castellum.castellum_auth.models import User

from ..forms import MemberForm
from ..forms import MultiMemberForm
from ..mixins import StudyMixin
from ..models import Study
from ..models import StudyMembership


class StudyMembersView(
    StudyMixin, PermissionRequiredMixin, SingleObjectMixin, FormView
):
    model = Study
    pk_url_kwarg = 'study_pk'
    template_name = 'studies/study_members.html'
    permission_required = 'studies.change_study'
    tab = 'members'

    def dispatch(self, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['membership_forms'] = [
            MemberForm(instance=membership)
            for membership in self.study.studymembership_set.all()
        ]
        return context

    def get_form(self):
        kwargs = self.get_form_kwargs()

        if 'membership' in self.request.POST:
            kwargs['instance'] = get_object_or_404(
                self.study.studymembership_set, pk=self.request.POST['membership']
            )

            form = MemberForm(**kwargs)
        else:
            form = MultiMemberForm(**kwargs)
            form.instance.study = self.object
            form.fields['users'].choices = [
                (user.pk, str(user))
                for user in User.objects.exclude(pk__in=self.object.members.all())
            ]

        return form

    def form_valid(self, form):
        form.instance.study = self.object

        def format_list(a):
            return [int(pk) for pk in sorted(a)]

        if 'membership' in self.request.POST:
            membership = StudyMembership.objects.get(pk=self.request.POST['membership'])
            old_groups = set(membership.groups.values_list('pk', flat=True))
            new_groups = {int(group) for group in self.request.POST.getlist('groups')}
            if old_groups != new_groups:
                audit(
                    gettext_noop('member changed'),
                    self.request.user.username,
                    study_pk=self.study.pk,
                    extra={
                        'member': membership.user.username,
                        'groups': format_list(new_groups),
                    },
                )
        else:
            for member in form.cleaned_data['users']:
                audit(
                    gettext_noop('member added'),
                    self.request.user.username,
                    study_pk=self.study.pk,
                    extra={
                        'member': member.username,
                        'groups': format_list(self.request.POST.getlist('groups')),
                    },
                )

        form.save()
        return redirect('studies:members', self.object.pk)


class StudyMembershipRemoveView(StudyMixin, PermissionRequiredMixin, DeleteView):
    model = StudyMembership
    permission_required = 'studies.change_study'
    tab = 'members'

    def get_object(self):
        return get_object_or_404(
            StudyMembership, pk=self.kwargs['pk'], study=self.study
        )

    def get_success_url(self):
        return reverse('studies:members', args=[self.study.pk])

    def form_valid(self, form):
        if self.object.user.pk == self.request.user.pk:
            return HttpResponseBadRequest()

        audit(
            gettext_noop('member removed'),
            self.request.user.username,
            study_pk=self.study.pk,
            extra={'member': self.object.user.username},
        )

        return super().form_valid(form)

castellum/studies/templates/studies/base.html
{% extends "base_with_breadcrumbs.html" %}

{% load i18n %}

{% block breadcrumbs %}
    <li class="breadcrumb-item"><a href="{% url 'studies:index' %}">{% translate "Studies" %}</a></li>
{% endblock %}

castellum/studies/templates/studies/filtergroup_confirm_delete.html
{% extends view.base_template|default:"studies/study_recruitmentsettings_base.html" %}
{% load i18n %}

{% block title %}{% translate "Delete Filter Group" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>{% translate "Are you sure you want to delete this filter group and all of its filters?" %}</p>
        <div class="d-print-none mb-3">
            <a href="{% url 'studies:filtergroup-index' object.study.pk %}" class="btn btn-outline-primary mb-1" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger mb-1">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

castellum/studies/templates/studies/study_audit_trail.html
{% extends "studies/study_base.html" %}
{% load i18n django_bootstrap5 %}

{% block title %}{% translate "Audit trail" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <ul class="table-list mb-3">
        {% for event in object_list %}
            <li class="table-list-item">
                <time class="text-secondary">{{ event.created_at }}</time>:
                {% translate event.action %} {% translate "by" %} {{ event.username }}
                {% if event.count > 1 %}
                    (×{{ event.count }})
                {% endif %}
            </li>
        {% empty %}
            <li class="alert alert-info">{% translate 'No audit events in the past year.' %}</li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <nav aria-label="{% translate 'Pagination' %}">
            {% bootstrap_pagination page_obj url=request.get_full_path %}
        </nav>
    {% endif %}
{% endblock %}

castellum/studies/templates/studies/study_base.html
{% extends "studies/base.html" %}
{% load i18n auth utils %}

{% block title %}{{ study }} &middot; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'studies:detail' study.pk %}">{{ study.name }}</a></li>
{% endblock %}

{% block header %}
    <div class="container text-center my-4">
        <div>
            <h1>{{ study }}</h1>
            {% for tag in study.tags.all %}
                <span class="badge text-bg-info">{{ tag }}</span>
            {% endfor %}
            {% if study.status != study.EXECUTION %}
                <span class="badge text-bg-secondary">{{ study.get_status_badge }}</span>
            {% endif %}

            <p class="text-body-secondary mt-2">
                <span class="d-inline-block mx-2">
                    {% icon 'user' label=study|verbose_name:'contact_person' %}
                    {{ study.contact_person }}
                </span>
                <span class="d-inline-block mx-2">
                    {% icon 'envelope' label=study|verbose_name:'email' %}
                    <a href="mailto:{{ study.email }}" class="text-reset">{{ study.email }}</a>
                </span>
                <span class="d-inline-block mx-2">
                    {% icon 'phone' label=study|verbose_name:'phone' %}
                    <a href="tel:{{ study.phone }}" class="text-reset">{{ study|display:'phone' }}</a>
                </span>
                {% if 'url' in CASTELLUM_ENABLE_STUDY_METADATA and study.url %}
                    <span class="d-block mx-2">
                        {% icon 'globe' label=study|verbose_name:'url' %}
                        <a href="{{ study.url }}" target="_blank" class="text-reset">{{ study|display:'url' }}</a>
                    </span>
                {% endif %}
            </p>
        </div>
        <div class="d-print-none">
            {% has_perm 'studies.change_study' user as can_add_study %}
            {% has_perm 'studies.access_study' user study as can_access_study %}
            {% has_perm 'studies.change_study' user study as can_change_study %}
            {% has_perm 'studies.delete_study' user study as can_delete_study %}
            {% has_perm 'studies.approve_study' user as can_approve_study %}
            {% if can_approve_study %}
                {% if study.status != study.FINISHED %}
                    <form class="d-inline" method="post" action="{% url 'studies:start' study.pk %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        {% if study.status == study.EXECUTION %}
                            <button class="btn btn-outline-primary active mb-1" title="{% translate 'Stop recruitment and execution for this study' %}">
                                {% translate 'Stop' %}
                            </button>
                        {% else %}
                            <button class="btn btn-outline-primary mb-1" title="{% translate 'Start recruitment and execution for this study' %}">
                                {% translate 'Start' %}
                            </button>
                        {% endif %}
                    </form>
                {% else %}
                    <form class="d-inline">
                        {% if study.previous_status == study.EXECUTION %}
                            <button class="btn btn-outline-primary active mb-1" title="{% translate 'Stop recruitment and execution for this study' %}" disabled>
                                {% translate 'Stop' %}
                            </button>
                        {% else %}
                            <button class="btn btn-outline-primary mb-1" title="{% translate 'Start recruitment and execution for this study' %}" disabled>
                                {% translate 'Start' %}
                            </button>
                        {% endif %}
                    </form>
                {% endif %}
            {% endif %}
            {% if can_access_study %}
                {% if can_change_study %}
                    <form class="d-inline" method="post" action="{% url 'studies:finish' study.pk %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">

                        {% if study.status == study.FINISHED %}
                            <button class="btn btn-outline-primary active mb-1" title="{% translate 'Resume recruitment and execution for this study' %}">
                                {% translate 'Resume study' %}
                            </button>
                        {% else %}
                            <a class="btn btn-outline-primary mb-1" href="{% url 'studies:finish' study.pk %}" title="{% translate 'Conclude recruitment and execution for this study' %}">
                                {% translate 'Finish study' %}…
                            </a>
                        {% endif %}
                    </form>
                    {% if can_add_study %}
                        <a href="{% url 'studies:create' %}?duplicate_pk={{ study.pk }}" class="btn btn-outline-primary mb-1">{% translate 'Duplicate' %}</a>
                    {% endif %}
                {% endif %}
                {% if study.status == study.FINISHED and can_delete_study %}
                    <a href="{% url 'studies:delete' study.pk %}" class="btn btn-danger mb-1">{% translate 'Delete' %}</a>
                {% endif %}
            {% endif %}
        </div>
    </div>

    <nav class="d-print-none" aria-label="{% translate 'Tabs' %}">
        {% has_perm 'studies.access_study' user study as can_access_study %}
        {% has_perm 'studies.change_study' user study as can_change_study %}
        {% has_perm 'studies.view_audit_trail' user study as can_view_audit_trail %}

        <ul class="nav nav-tabs justify-content-center mb-3">
            <li class="nav-item">
                <a class="nav-link {% if view.tab == 'detail' %}active{% endif %}" href="{% url 'studies:detail' study.pk %}">{% translate 'Overview' %}</a>
            </li>

            {% if can_access_study and can_change_study %}
                <li class="nav-item">
                    <a class="nav-link {% if view.tab == 'update' %}active{% endif %}" href="{% url 'studies:update' study.pk %}">{% translate 'General' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view.tab == 'members' %}active{% endif %}" href="{% url 'studies:members' study.pk %}">{% translate 'Member management' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view.tab == 'consent' %}active{% endif %}" href="{% url 'studies:consent' study.pk %}">{% translate 'Consent' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view.tab == 'domains' %}active{% endif %}" href="{% url 'studies:domains' study.pk %}">
                        {% translate 'Pseudonym lists' %}
                        {% if study.should_enter_pseudonyms_delete_date or study.should_delete_domains %}
                            {% icon 'exclamation-triangle' label=_('Action required') %}
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view.tab == 'sessions' %}active{% endif %}" href="{% url 'studies:sessions' study.pk %}">
                        {% translate 'Sessions' %}
                        {% if study.should_enter_sessions_end or study.should_finish_study %}
                            {% icon 'exclamation-triangle' label=_('Action required') %}
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if view.tab == 'recruitmentsettings' %}active{% endif %}" href="{% url 'studies:recruitmentsettings' study.pk %}">{% translate 'Recruitment Settings' %}</a>
                </li>
            {% endif %}
            {% if CASTELLUM_AUDIT_TRAIL_ENABLED and can_view_audit_trail %}
                <li class="nav-item">
                    <a class="nav-link {% if view.tab == 'audit-trail' %}active{% endif %}" href="{% url 'studies:audit-trail' study.pk %}">{% translate 'Audit trail' %}</a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

castellum/studies/templates/studies/study_consent.html
{% extends "studies/study_base.html" %}
{% load static i18n django_bootstrap5 utils %}

{% block title %}{% translate "Consent" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% include 'utils/form_errors.html' with form=form %}
        {% csrf_token %}

        {% bootstrap_field form.consent required_css_class='castellum-required' %}

        <div class="d-print-none mb-3">
            <button class="btn btn-primary">{% translate 'Save' %}</button>
        </div>
    </form>
{% endblock %}

castellum/studies/templates/studies/study_domains_general.html
{% extends "studies/study_domains_base.html" %}
{% load i18n auth django_bootstrap5 utils %}

{% block title %}{% translate "General pseudonym lists" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post" class="mb-3" data-js="d-select2">
        {% include 'utils/form_errors.html' with form=form %}
        {% csrf_token %}
        <p>{% translate 'General pseudonym lists allow you to access pseudonyms for data that is shared via central repositories. Please note these pseudonyms allow to identify subjects globally and therefore carry a high privacy risk.' %}</p>
        {% bootstrap_field form.general_domains %}
        <button class="btn btn-primary">{% translate 'Save' %}</button>
    </form>
{% endblock %}

castellum/studies/templates/studies/study_filtertrial_base.html
{% extends "studies/base.html" %}
{% load i18n auth utils %}

{% block title %}{% translate 'Filter trial' %} &middot; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item">{% translate 'Filter trial' %}</li>
{% endblock %}

{% block container_class %}container-lg{% endblock %}

{% block header %}
    <div class="container text-center my-4">
        <h1>{% translate 'Filter trial' %}</h1>
    </div>
{% endblock %}

{% block content_with_messages %}
    <div class="row">
        <div class="col-md-3">
            <nav class="list-group mb-3" aria-label="{% translate 'Subtabs' %}">
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'update' %}active{% endif %}" href="{% url 'studies:recruitmentsettings' study.pk %}">{% translate 'General' %}</a>

                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'filters' %}active{% endif %}" href="{% url 'studies:filtergroup-index' study.pk %}">
                    {% translate 'Filters' %}
                </a>

                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'other-studies' %}active{% endif %}" href="{% url 'studies:other-studies' study.pk %}">{% translate 'Other studies' %}</a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'convert' %}active{% endif %}" href="{% url 'studies:filtertrial-convert' study.pk %}">{% translate 'Convert to study' %}</a>
            </nav>
        </div>

        <div class="col-md-9">
            {{ block.super }}
        </div>
    </div>
{% endblock %}

castellum/studies/templates/studies/studysession_confirm_delete.html
{% extends "studies/study_base.html" %}
{% load static i18n %}

{% block title %}{% translate "Delete session" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>{% blocktranslate with name=object.name %}Are you sure you want to <strong>permanently delete</strong> the session "{{ name }}" and all related appointments?{% endblocktranslate %}</p>
        <div class="d-print-none mb-3">
            <a href="{% url 'studies:sessions' study.pk %}" class="btn btn-outline-primary" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}