castellum/execution/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.urls import path

from .api import APIAttributesView
from .api import APIDomainsView
from .api import APIPseudonymsView
from .api import APIResolveView
from .api import APIValidateView
from .feeds import AppointmentFeedForUser
from .views import AdditionalInfoUpdateView
from .views import AttributesUpdateView
from .views import CalendarView
from .views import ConsentChangeView
from .views import ContactUpdateView
from .views import DataProtectionUpdateView
from .views import ExclusionCriteriaView
from .views import ExportView
from .views import LegalRepresentativeContactUpdateView
from .views import NewsMailView
from .views import ParticipationAppointmentsUpdateView
from .views import ParticipationConsentCreateView
from .views import ParticipationConsentDeleteView
from .views import ParticipationConsentView
from .views import ParticipationDetailView
from .views import ParticipationDropoutConfirmView
from .views import ParticipationListView
from .views import ParticipationPseudonymsView
from .views import ParticipationPseudonymView
from .views import ParticipationStatusView
from .views import ParticipationUpdateView
from .views import ProgressView
from .views import ReportView
from .views import ResolveView
from .views import TagView

app_name = 'execution'
urlpatterns = [
    path('calendar/feed/', AppointmentFeedForUser.as_view(), name='calendar-user-feed'),
    path('<int:study_pk>/', ParticipationListView.as_view(), name='participation-list'),
    path('<int:study_pk>/resolve/', ResolveView.as_view(), name='resolve'),
    path('<int:study_pk>/news/', NewsMailView.as_view(), name='news-mail'),
    path('<int:pk>/calendar/', CalendarView.as_view(), name='calendar'),
    path('<int:pk>/criteria/', ExclusionCriteriaView.as_view(), name='criteria'),
    path('<int:pk>/export/', ExportView.as_view(), name='export'),
    path('<int:pk>/progress/', ProgressView.as_view(), name='progress'),
    path('<int:pk>/tags/', TagView.as_view(), name='execution-tags'),
    path(
        '<int:study_pk>/<int:pk>/',
        ParticipationDetailView.as_view(),
        name='participation-detail',
    ),
    path(
        '<int:study_pk>/<int:pk>/pseudonyms/',
        ParticipationPseudonymsView.as_view(),
        name='participation-pseudonyms',
    ),
    path(
        '<int:study_pk>/<int:pk>/pseudonyms/<domain>/',
        ParticipationPseudonymView.as_view(),
        name='participation-pseudonym',
    ),
    path(
        '<int:study_pk>/<int:pk>/status/',
        ParticipationStatusView.as_view(),
        name='participation-status',
    ),
    path(
        '<int:study_pk>/<int:pk>/dropout/confirm/',
        ParticipationDropoutConfirmView.as_view(),
        name='participation-dropout-confirm',
    ),
    path(
        '<int:study_pk>/<int:pk>/update/',
        ParticipationUpdateView.as_view(),
        name='participation-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/consent/',
        ParticipationConsentView.as_view(),
        name='participation-consent',
    ),
    path(
        '<int:study_pk>/<int:pk>/consent/add/',
        ParticipationConsentCreateView.as_view(),
        name='participation-consent-create',
    ),
    path(
        '<int:study_pk>/<int:pk>/consent/<int:consent_pk>/delete/',
        ParticipationConsentDeleteView.as_view(),
        name='participation-consent-delete',
    ),
    path(
        '<int:study_pk>/<int:pk>/appointments/',
        ParticipationAppointmentsUpdateView.as_view(),
        name='participation-appointments',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-contact/',
        ContactUpdateView.as_view(),
        name='contact-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-attributes/',
        AttributesUpdateView.as_view(),
        name='attributes-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-data-protection/',
        DataProtectionUpdateView.as_view(),
        name='data-protection-update',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-data-protection/consent/',
        ConsentChangeView.as_view(),
        name='consent-change',
    ),
    path(
        '<int:study_pk>/<int:pk>/update-additional-info/',
        AdditionalInfoUpdateView.as_view(),
        name='additional-info-update',
    ),
    path(
        '<int:study_pk>/<int:participation_pk>/representatives/<hash>/update-contact/',
        LegalRepresentativeContactUpdateView.as_view(),
        name='legal-representative-contact-update',
    ),
    path('<int:study_pk>/<int:pk>/report/', ReportView.as_view(), name='report'),
]

if settings.CASTELLUM_API_ENABLED:
    urlpatterns += [
        path('api/studies/<int:pk>/domains/', APIDomainsView.as_view()),
        path(
            'api/studies/<int:pk>/domains/<uuid:domain>/', APIPseudonymsView.as_view()
        ),
        path(
            'api/studies/<int:pk>/domains/<uuid:domain>/<pseudonym>/',
            APIValidateView.as_view(),
        ),
        path(
            'api/studies/<int:study_pk>/domains/<uuid:domain>/<pseudonym>/attributes/',
            APIAttributesView.as_view(),
        ),
        path(
            'api/studies/<int:study_pk>/domains/<uuid:domain>/<pseudonym>/<uuid:target_domain>/',
            APIResolveView.as_view(),
        ),
    ]

castellum/subjects/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from django.conf import settings
from django.urls import path

from .api import APIAttributesView
from .views import AdditionalInfoUpdateView
from .views import AttributesUpdateView
from .views import ConsentChangeView
from .views import ContactUpdateView
from .views import DataProtectionUpdateView
from .views import DeleteRecruitmentDataView
from .views import LegalRepresentativeSearchView
from .views import MaintenanceAttributesView
from .views import MaintenanceConsentView
from .views import MaintenanceContactView
from .views import MaintenanceDuplicatesView
from .views import MaintenanceEstrangedSubjectsView
from .views import MaintenanceReliabilityView
from .views import MaintenanceSubjectCreationRequestView
from .views import ParticipationAddView
from .views import ParticipationDeleteView
from .views import ParticipationListView
from .views import ParticipationRecruitView
from .views import ReportDetailView
from .views import ReportView
from .views import SubjectAuditTrailView
from .views import SubjectCreationRequestDeleteView
from .views import SubjectDeleteView
from .views import SubjectDetailView
from .views import SubjectExportView
from .views import SubjectPseudonymsView
from .views import SubjectPseudonymView
from .views import SubjectResolveView
from .views import SubjectSearchView

app_name = 'subjects'
urlpatterns = [
    path('', SubjectSearchView.as_view(), name='index'),
    path('resolve/', SubjectResolveView.as_view(), name='resolve'),
    path(
        'representatives/',
        LegalRepresentativeSearchView.as_view(),
        name='legal-representative-search',
    ),
    path(
        'maintenance/attributes/',
        MaintenanceAttributesView.as_view(),
        name='maintenance-attributes',
    ),
    path(
        'maintenance/contact/',
        MaintenanceContactView.as_view(),
        name='maintenance-contact',
    ),
    path(
        'maintenance/consent/',
        MaintenanceConsentView.as_view(),
        name='maintenance-consent',
    ),
    path(
        'maintenance/duplicates/',
        MaintenanceDuplicatesView.as_view(),
        name='maintenance-duplicates',
    ),
    path(
        'maintenance/reliability/',
        MaintenanceReliabilityView.as_view(),
        name='maintenance-reliability',
    ),
    path(
        'maintenance/estranged-subjects/',
        MaintenanceEstrangedSubjectsView.as_view(),
        name='maintenance-estranged-subjects',
    ),
    path(
        'maintenance/subjectcreationrequest/',
        MaintenanceSubjectCreationRequestView.as_view(),
        name='maintenance-subjectcreationrequest',
    ),
    path(
        'subjectcreationrequest/<int:pk>/delete/',
        SubjectCreationRequestDeleteView.as_view(),
        name='maintenance-subjectcreationrequest-delete',
    ),
    path('<uuid:pk>/', SubjectDetailView.as_view(), name='detail'),
    path('<uuid:pk>/pseudonyms/', SubjectPseudonymsView.as_view(), name='pseudonyms'),
    path(
        '<uuid:pk>/pseudonyms/<domain>/',
        SubjectPseudonymView.as_view(),
        name='pseudonym',
    ),
    path('<uuid:pk>/delete/', SubjectDeleteView.as_view(), name='delete'),
    path('<uuid:pk>/export/', SubjectExportView.as_view(), name='export'),
    path('<uuid:pk>/contact/', ContactUpdateView.as_view(), name='contact'),
    path('<uuid:pk>/attributes/', AttributesUpdateView.as_view(), name='attributes'),
    path(
        '<uuid:pk>/attributes/delete/',
        DeleteRecruitmentDataView.as_view(),
        name='delete-recruitment-data',
    ),
    path(
        '<uuid:pk>/data-protection/',
        DataProtectionUpdateView.as_view(),
        name='data-protection',
    ),
    path(
        '<uuid:pk>/data-protection/consent/',
        ConsentChangeView.as_view(),
        name='consent',
    ),
    path(
        '<uuid:pk>/additional-info/',
        AdditionalInfoUpdateView.as_view(),
        name='additional-info',
    ),
    path(
        '<uuid:pk>/participations/',
        ParticipationListView.as_view(),
        name='participation-list',
    ),
    path(
        '<uuid:pk>/participations/recruit/',
        ParticipationRecruitView.as_view(),
        name='participation-recruit',
    ),
    path(
        '<uuid:pk>/participations/add/',
        ParticipationAddView.as_view(),
        name='participation-add',
    ),
    path(
        '<uuid:subject_uuid>/participations/<int:pk>/delete/',
        ParticipationDeleteView.as_view(),
        name='participation-delete',
    ),
    path('<uuid:pk>/report/', ReportView.as_view(), name='report'),
    path('reports/<int:pk>/', ReportDetailView.as_view(), name='report-detail'),
]

if settings.CASTELLUM_AUDIT_TRAIL_ENABLED:
    urlpatterns += [
        path(
            '<uuid:pk>/audit-trail/',
            SubjectAuditTrailView.as_view(),
            name='audit-trail',
        ),
    ]

if settings.CASTELLUM_API_ENABLED:
    urlpatterns += [
        path(
            'api/subjects/<uuid:domain>/<pseudonym>/attributes/',
            APIAttributesView.as_view(),
        ),
    ]

castellum/urls.py
# SPDX-FileCopyrightText: 2018-2025 MPIB <https://www.mpib-berlin.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPI-CBS <https://www.cbs.mpg.de/>
# SPDX-FileCopyrightText: 2018-2019 MPIP <http://www.psych.mpg.de/>
# SPDX-License-Identifier: AGPL-3.0-or-later

from bootstrap_colors.views import BootstrapColorsView
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.urls import include
from django.urls import path
from django.views.decorators.cache import cache_control
from django.views.generic import RedirectView
from django.views.generic import TemplateView
from mfa.decorators import public as mfa_public
from mfa.views import LoginView
from stronghold.decorators import public

from castellum.castellum_auth.forms import AuthenticationForm
from castellum.castellum_auth.views import set_language
from castellum.execution.views import ExecutionProtectedMediaView
from castellum.execution.views import StudyConsentProtectedMediaView
from castellum.recruitment.views import RecruitmentProtectedMediaView
from castellum.studies.models import Resource
from castellum.studies.models import Study
from castellum.studies.views.studies import StudyProtectedMediaView
from castellum.subjects.views import SubjectProtectedMediaView
from castellum.utils.views import ProtectedMediaView


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'index.html'


class FeedsView(LoginRequiredMixin, TemplateView):
    template_name = 'feeds.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['resources'] = Resource.objects.all()
        context['studies'] = self.request.user.study_set.filter(status=Study.EXECUTION)
        return context


def dummy(request):
    return HttpResponse('', status=204)


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(
        template_name='login.html',
        authentication_form=AuthenticationForm,
    ), name='login'),
    path('logout/', mfa_public(LogoutView.as_view()), name='logout'),
    path('favicon.ico', mfa_public(public(
        RedirectView.as_view(url='/static/images/favicon.ico')
    ))),
    path('colors.css', mfa_public(public(cache_control(max_age=86400)(
        BootstrapColorsView.as_view()
    ))), name='colors'),
    path('ping/', dummy, name='ping'),
    path('feeds/', FeedsView.as_view(), name='feeds'),

    path('i18n/', mfa_public(set_language), name='set_language'),

    path('admin/', admin.site.urls),
    path('studies/', include('castellum.studies.urls', namespace='studies')),
    path('subjects/', include('castellum.subjects.urls', namespace='subjects')),
    path('contacts/', include('castellum.contacts.urls', namespace='contacts')),
    path(
        'recruitment/', include('castellum.recruitment.urls', namespace='recruitment')
    ),
    path('execution/', include('castellum.execution.urls', namespace='execution')),
    path('', include('castellum.appointments.urls', namespace='appointments')),
    path(
        'data-protection/',
        include('castellum.data_protection.urls', namespace='data_protection'),
    ),
    path('mfa/', include('mfa.urls', namespace='mfa')),

    path('media/studies/<int:pk>/<path:path>', StudyProtectedMediaView.as_view()),
    path(
        'media/recruitment/<int:study_pk>/<int:pk>/<path:path>',
        RecruitmentProtectedMediaView.as_view(),
        name='recruitment-media',
    ),
    path(
        'media/execution/<int:study_pk>/<int:pk>/<path:path>',
        ExecutionProtectedMediaView.as_view(),
        name='execution-media',
    ),
    path(
        'media/studyconsents/<int:study_pk>/<int:pk>/<filename>',
        StudyConsentProtectedMediaView.as_view(),
        name='studyconsent-media',
    ),
    path(
        'media/subjects/<uuid:uuid>/<path:path>',
        SubjectProtectedMediaView.as_view(),
        name='subject-media',
    ),
    path('media/consent/<path:path>', ProtectedMediaView.as_view(prefix='consent')),
]

if 'model_stats' in settings.INSTALLED_APPS:
    urlpatterns = [
        path('admin/stats/', include('model_stats.urls')),
        *urlpatterns,
    ]

try:
    import debug_toolbar

    urlpatterns = [
        *urlpatterns,
        path('__debug__/', include(debug_toolbar.urls)),
    ]
except ImportError:
    pass

castellum/subjects/templates/subjects/confirm_delete_recruitment_data.html
{% extends "subjects/subject_base.html" %}
{% load static i18n %}

{% block title %}{% translate "Delete recruitment data" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>{% translate "Are you sure you want to <strong>permanently delete</strong> all recruitment attributes and study type disinterests for this subject?" %}</p>
        <div class="d-print-none mb-3">
            <a href="{% url 'subjects:attributes' subject.pk %}" class="btn btn-outline-primary" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

castellum/subjects/templates/subjects/maintenance_base.html
{% extends "subjects/base.html" %}
{% load i18n %}

{% block container_class %}container-lg{% endblock %}

{% block title %}{% translate 'Maintenance' %} &middot; {{ block.super }}{% endblock %}

{% block header %}
    <div class="container text-center my-4">
        <h1>{% translate 'Maintenance' %}</h1>
    </div>
{% endblock %}

{% block content_with_messages %}
    <div class="row">
        <div class="col-md-3">
            <nav class="list-group mb-3" aria-label="{% translate 'Subtabs' %}">
                <a href="{% url 'subjects:maintenance-attributes' %}" class="list-group-item list-group-item-custom list-group-item-action {% if view.tab == 'attributes' %}active{% endif %}">{% translate 'Recruitment attributes' %}</a>
                <a href="{% url 'subjects:maintenance-contact' %}" class="list-group-item list-group-item-custom list-group-item-action {% if view.tab == 'contact' %}active{% endif %}">{% translate 'Contact data' %}</a>
                <a href="{% url 'subjects:maintenance-duplicates' %}" class="list-group-item list-group-item-custom list-group-item-action {% if view.tab == 'duplicates' %}active{% endif %}">{% translate 'Potential duplicates' %}</a>
                <a href="{% url 'subjects:maintenance-consent' %}" class="list-group-item list-group-item-custom list-group-item-action {% if view.tab == 'consent' %}active{% endif %}">{% translate 'Outdated consent' %}</a>
                <a href="{% url 'subjects:maintenance-reliability' %}" class="list-group-item list-group-item-custom list-group-item-action {% if view.tab == 'reliability' %}active{% endif %}">{% translate 'Reliability' %}</a>
                <a href="{% url 'subjects:maintenance-estranged-subjects' %}" class="list-group-item list-group-item-custom list-group-item-action {% if view.tab == 'estranged_subjects' %}active{% endif %}">{% translate 'Estranged subjects' %}</a>
                {% if CASTELLUM_SUBJECT_CREATION_REQUESTS_ENABLED %}
                    <a href="{% url 'subjects:maintenance-subjectcreationrequest' %}" class="list-group-item list-group-item-custom list-group-item-action {% if view.tab == 'subjectcreationrequest' %}active{% endif %}">{% translate 'Subject creation requests' %}</a>
                {% endif %}
            </nav>
        </div>

        <div class="col-md-9">
            {{ block.super }}
        </div>
    </div>
{% endblock %}

castellum/subjects/templates/subjects/maintenance_estranged_subjects.html
{% extends "subjects/maintenance_base.html" %}
{% load i18n django_bootstrap5 auth %}

{% block title %}{% translate "Estranged subjects" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <p>{% translate 'The following subjects have not been contacted for a long time:' %}</p>

    <ul class="table-list">
        {% for subject in object_list %}
            {% has_privacy_level subject.privacy_level user as can_access %}
            <li class="table-list-item">
                <svg class="identicon my-1 me-2" data-jdenticon-value="{{ subject.pk }}" aria-hidden="true"></svg>
                <div>
                    <div>{% translate 'Last contacted on' %}: {{ subject.updated_at|date }}</div>
                </div>
                <div class="table-list-item-actions">
                    {% if can_access %}
                        <a class="btn btn-outline-primary my-1" href="{% url 'subjects:detail' subject.pk %}" target="_blank">{% translate 'Details' %}</a>
                    {% else %}
                        <button class="btn btn-outline-primary my-1" disabled>{% translate 'Details' %}</button>
                    {% endif %}
                </div>
            </li>
        {% empty %}
            <li class="alert alert-success">{% translate 'Nothing to do' %}</li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <nav aria-label="{% translate 'Pagination' %}">
            {% bootstrap_pagination page_obj url=request.get_full_path %}
        </nav>
    {% endif %}
{% endblock %}

castellum/subjects/templates/subjects/maintenance_reliability.html
{% extends "subjects/maintenance_base.html" %}
{% load i18n django_bootstrap5 auth utils %}

{% block title %}{% translate "Reliability" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <p>{% translate 'The following subjects have a record of coming late or not at all:' %}</p>

    <ul class="table-list">
        {% for subject in object_list %}
            {% has_privacy_level subject.privacy_level user as can_access %}
            <li class="table-list-item">
                <svg class="identicon my-1 me-2" data-jdenticon-value="{{ subject.pk }}" aria-hidden="true"></svg>
                <div>
                    <div>{{ subject|display:'reliability' }}</div>
                    <div>{% translate 'Last contacted on' %}: {{ subject.updated_at|date }}</div>
                </div>
                <div class="table-list-item-actions">
                    {% if can_access %}
                        <a class="btn btn-outline-primary my-1" href="{% url 'subjects:detail' subject.pk %}" target="_blank">{% translate 'Details' %}</a>
                    {% else %}
                        <button class="btn btn-outline-primary my-1" disabled>{% translate 'Details' %}</button>
                    {% endif %}
                </div>
            </li>
        {% empty %}
            <li class="alert alert-success">{% translate 'Nothing to do' %}</li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <nav aria-label="{% translate 'Pagination' %}">
            {% bootstrap_pagination page_obj url=request.get_full_path %}
        </nav>
    {% endif %}
{% endblock %}

castellum/subjects/templates/subjects/participation_base.html
{% extends "subjects/subject_base.html" %}
{% load i18n auth %}

{% block title %}{% translate "Study Participations" %} &middot; {{ block.super }}{% endblock %}

{% block container_class %}container-lg{% endblock %}

{% block content_with_messages %}
    <div class="row">
        <div class="col-md-3">
            <nav class="list-group mb-3" aria-label="{% translate 'Subtabs' %}">
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'list' %}active{% endif %}" href="{% url 'subjects:participation-list' subject.pk %}">{% translate 'Participating' %}</a>
                <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'recruit' %}active{% endif %}" href="{% url 'subjects:participation-recruit' subject.pk %}">{% translate 'Matching studies' %}</a>
                {% has_perm 'subjects.change_subject' user as can_change_subject %}
                {% if can_change_subject %}
                    <a class="list-group-item list-group-item-custom list-group-item-action {% if view.subtab == 'add' %}active{% endif %}" href="{% url 'subjects:participation-add' subject.pk %}">{% translate 'Add to study' %}</a>
                {% endif %}
            </nav>
        </div>

        <div class="col-md-9">
            {{ block.super }}
        </div>
    </div>
{% endblock %}

castellum/subjects/templates/subjects/subject_confirm_delete.html
{% extends "subjects/subject_base.html" %}
{% load i18n auth subjects utils %}

{% block title %}{% translate "Delete subject" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}

        {% if is_last_legal_representative %}
            <p class="alert alert-danger">
                {% translate "This person is the only legal representative of another subject. Deletion means that the subject represented by this person becomes unreachable!" %}
            </p>
        {% endif %}

        {% if has_participations %}
            <p class="alert alert-danger">
                {% translate "This subject cannot be deleted because there still is data about them in studies." %}
            </p>
        {% elif has_pseudonym_in_general_domain %}
            <p class="alert alert-warning">
                {% translate "This subject may still have data from general pseudonym lists." %}
            </p>
        {% else %}
            <p class="alert alert-success">
                {% translate "This subject does not have any data in studies that would block deletion." %}
            </p>
        {% endif %}

        {% if has_participations or has_pseudonym_in_general_domain %}
            <div class="card my-4">
                <div class="card-body">
                    {% if has_participations %}
                        <p>{% translate "Please delete all of these study participations:" %}</p>
                    {% endif %}

                    <ul class="table-list mb-3">
                        {% for participation in object.participation_set.all %}
                            {% has_perm 'studies.view_study' user participation.study as can_view_study %}
                            <li class="table-list-item">
                                <div class="my-1 me-2">
                                    <div class="h4 d-inline">{{ participation.study }}</div>
                                    <span class="badge text-bg-secondary" title="{{ participation.get_status_tooltip }}">{{ participation|display:'status' }}</span>
                                    {% if participation.study.status == participation.study.FINISHED and not participation.study.domains.exists %}
                                        <span class="badge text-bg-secondary" title="{{ participation.TOOLTIPS.pseudonyms_deleted }}">{% translate 'Pseudonyms deleted' %}</span>
                                    {% endif %}
                                    <div class="my-1">
                                        {% icon 'user' label=participation.study|verbose_name:'contact_person' %}
                                        {{ participation.study.contact_person }}
                                    </div>
                                </div>
                                <div class="table-list-item-actions">
                                    {% if participation.status in participation.INVITED_SET %}
                                        <a class="btn btn-outline-primary my-1" href="{% url 'execution:participation-pseudonyms' participation.study.pk participation.pk %}">{% translate 'Pseudonyms' %}</a>
                                        <a class="btn btn-outline-primary my-1" href="{% delete_mail_uri participation %}">{% translate 'Mail to study' %}</a>
                                    {% endif %}
                                    {% if can_view_study %}
                                        <a class="btn btn-outline-primary my-1" href="{% url 'studies:detail' participation.study.pk %}">{% translate 'Study details' %}</a>
                                    {% endif %}
                                    <a class="btn btn-danger my-1" href="{% url 'subjects:participation-delete' subject.pk participation.pk %}">
                                        {% translate 'Delete' %}
                                    </a>
                                </div>
                            </li>
                        {% endfor %}
                        {% if has_pseudonym_in_general_domain %}
                            <li class="table-list-item">
                                <div class="my-1 me-2">
                                    <div class="h4 d-inline">{% translate "General pseudonym lists" %}</div>
                                </div>
                                <div class="table-list-item-actions">
                                    <a class="btn btn-outline-primary my-1" href="{% url 'subjects:pseudonyms' subject.pk %}">{% translate 'Pseudonyms' %}</a>
                                </div>
                            </li>
                        {% endif  %}
                    </ul>
                </div>
            </div>
        {% endif %}

        <p>{% translate "Are you sure you want to <strong>permanently delete</strong> this subject and all related data?" %}</p>
        {% if not has_participations and has_pseudonym_in_general_domain %}
            <label class="form-check mb-3">
                <input type="checkbox" class="form-check-input" data-js="confirm-delete">
                <span class="form-check-label">{% translate "I have made sure that all external data related to this subject is either covered by retention periods or has been destroyed." %}</span>
            </label>
        {% endif %}
        <div class="d-print-none mb-3">
            <a href="{% url 'subjects:detail' object.pk %}" class="btn btn-outline-primary mb-1" data-js="cancel">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger mb-1" {% if has_participations or has_pseudonym_in_general_domain %}disabled{% endif %} >{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}